on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: file commands
              uses: appleboy/ssh-action@v1
              with:
                  host: hackclub.app
                  username: kierank
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script_path: update.sh
